# Generated by Django 5.2.14 on 2026-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=8)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbohydrates in grams', max_digits=8)),
                ('fats', models.DecimalField(decimal_places=2, help_text='Fats in grams', max_digits=8)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, help_text='Fiber in grams', max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, help_text='Sugar in grams', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
