# Generated by Django 5.2.14 on 2026-05-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default='food/default-image', null=True, upload_to='food'),
        ),
    ]
