# Generated by Django 5.2.14 on 2026-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default='food/default-image.jpg', null=True, upload_to='food'),
        ),
    ]
