# Generated by Django 5.2.14 on 2026-05-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
