# Generated by Django 5.2.14 on 2026-05-25 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='consumed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
